import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import fetch from "isomorphic-unfetch";
import Link from 'next/link'

const Home=({notes})=> {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      
      </Head>

      <h1>Notes</h1>

      <div className="grid wrapper">
        {
          notes.map(note => {
            return (
              <div key={note._id} className="container-fluid">
                <div className="card">
                  <div className="card-body">
                    <h5>{note.title}</h5>
                    <Link href={`/${note._id}`}>
                    <a className="card-link">View</a>
                    </Link>
                    <Link href={`/${note._id}/edit`}>
                    <a className="card-link">Edit</a>
                    </Link>
                  </div>
                </div>
                </div>
            )
          })
      }
      </div>
      
     
    </div>
  )
}

Home.getInitialProps = async () => {
  const res = await fetch('http://localhost:3000/api/notes');
  const { data } = await res.json();

  return {notes: data}
}

export default Home